### ISSUE TITLE
Investigate moving value/policy head to GPU

### ISSUE THREAD

**Issue by glinscott** [glinscott/leela-chess#51]
There was a prototype here: https://github.com/ihavnoid/leela-zero/tree/dualhead_conv

It was not a win for Leela Zero, but with us increasing from 1/2 to 32 or 64 channels, it could make a big difference now.

**Comment by Error323** [comment]
I'm looking into this. It's not as trivial as I had hoped.

**Comment by gcp** [comment]
https://github.com/gcp/leela-zero/commit/f4a36c1b4e44a28b1d607f0868bfeb67f9db9b80

This doesn't move the entire head (i.e. not the FC/innerproduct layers), just the final 1x1 convolution. It's useful because it saves a lot of data transfer (64-128 fold!) over the PCIe bus.

**Comment by Error323** [comment]
Hi @gcp @glinscott I'm trying to get @gcp's f4a36c1 to work, but I'm not experienced enough in OpenCL. I'm a CUDA guy mostly and this is taking a lot of time :/. I was hoping if one of you could take a stab at why or point me in the right direction. How do I debug this properly? [my attempt](https://github.com/Error323/leela-chess/commit/e073958e769dbad5348aa44eba8ef2b73a9a38b2) isn't working. Here is the gdb backtrace:

```
#0  0x00007ffff550e428 in __GI_raise (sig=sig@entry=0x6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff551002a in __GI_abort () at abort.c:89
#2  0x00007ffff606e84d in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff606c6b6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff606c701 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff606c919 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00000000005207ee in cl::detail::errHandler (err=0xfffffffc, errStr=0x55aaea "clEnqueueWriteBuffer") at /home/fhuizing/Workspace/chess/leela-chess/src/CL/cl2.hpp:764
#7  0x000000000052652c in cl::CommandQueue::enqueueWriteBuffer (this=0x7ffff7fc1738, buffer=..., blocking=0x0, offset=0x0, size=0x7800, ptr=0x2fb4680, events=0x0, event=0x0) at /home/fhuizing/Workspace/chess/leela-chess/src/CL/cl2.hpp:7180
#8  0x000000000052166a in OpenCL_Network::forward (this=0x18d9af0, input=std::vector of length 7680, capacity 7680 = {...}, output_pol=std::vector of length 2048, capacity 2048 = {...}, output_val=std::vector of length 2048, capacity 2048 = {...}) at /home/fhuizing/Workspace/chess/leela-chess/src/OpenCL.cpp:504
#9  0x00000000005063b1 in OpenCLScheduler::forward (this=0x17af8a0 <opencl>, input=std::vector of length 7680, capacity 7680 = {...}, output_pol=std::vector of length 2048, capacity 2048 = {...}, output_val=std::vector of length 2048, capacity 2048 = {...}) at /home/fhuizing/Workspace/chess/leela-chess/src/OpenCLScheduler.cpp:72
#10 0x00000000004f7590 in Network::get_scored_moves_internal (pos=..., planes=..., debug_data=0x0) at /home/fhuizing/Workspace/chess/leela-chess/src/Network.cpp:907
#11 0x00000000004f710d in Network::get_scored_moves (pos=..., debug_data=0x0) at /home/fhuizing/Workspace/chess/leela-chess/src/Network.cpp:873
#12 0x00000000005491e6 in UCTNode::create_children (this=0x30b3a10, nodecount=..., state=..., eval=@0x7fffffffd92c: 0) at /home/fhuizing/Workspace/chess/leela-chess/src/UCTNode.cpp:80
#13 0x0000000000532be1 in UCTSearch::think (this=0x30b39e0) at /home/fhuizing/Workspace/chess/leela-chess/src/UCTSearch.cpp:256
#14 0x000000000051e9be in (anonymous namespace)::go (bh=..., is=...) at /home/fhuizing/Workspace/chess/leela-chess/src/UCI.cpp:139
#15 0x000000000051f5aa in UCI::loop (start="") at /home/fhuizing/Workspace/chess/leela-chess/src/UCI.cpp:325
#16 0x00000000004d4b70 in main (argc=0x3, argv=0x7fffffffde48) at /home/fhuizing/Workspace/chess/leela-chess/src/main.cpp:331
```

This happens after loading a weight file and running a search with the `go` command:
```
go
terminate called after throwing an instance of 'cl::Error'
  what():  clEnqueueWriteBuffer
```

**Comment by glinscott** [comment]
Resolved by #64.  Thanks @Error323!

**Comment by Ttl** [comment]
#64 only moved the convolutions to GPU. Innerproducts are still on CPU and according to the profiler take more time than convolutions on GPU.

I made earlier a GPU innerproduct for leelaz, but it was slower than doing it on CPU. It should be faster for lczero since innerproducts are much bigger. I'll see if I can port it over.

**Comment by Error323** [comment]
Hey @glinscott sorry it's not fully resolved yet, we should still move the innerproducts to the GPU, atleast the policy head 32*8*8 -> 1924 and the 32*8*8 -> 128 from the valuehead.

**Comment by glinscott** [comment]
Ah, yes, good call @Error323.  After some quick work by @Ttl the innerproducts are now moved to GPU as well!  Thanks @Ttl!
