### ISSUE TITLE
colab's disconnection

### ISSUE THREAD

**Issue by lehpo** [glinscott/leela-chess#523]
colab keeps disconnecting

can someone fix this issue asap?

thanks very much

**Comment by kpu3uc** [comment]
https://i.imgur.com/PLtPp86.png
No URLs found in -. error

**Comment by lehpo** [comment]
is colab down?

i can't connect now

**Comment by robinhouston** [comment]
@kpu3uc This is fixed in the current version of [the notebook](https://colab.research.google.com/drive/1nGIZyvmGdyOXGLnBGx0JqSSt6PsXeim1).

**Comment by lehpo** [comment]
robin, i'm still getting the same message. this issue needs 2 b fixed asap.
many others are experiencing my same situation, which means that many self
training games are being lost

**Comment by Drefsante** [comment]
I just have changed the line:

!cd leela-chess/build && wget https://github.com/glinscott/leela-chess/releases/download/v0.7/client_linux -O client_linux && chmod +x client_linux

by:

!cd leela-chess/build && wget https://github.com/glinscott/leela-chess/releases/download/v0.8rc1/client_linux -O client_linux && chmod +x client_linux

and it works...

**Comment by kpu3uc** [comment]
!cd leela-chess/build && curl -s -L https://github.com/glinscott/leela-chess/releases/latest | egrep -o '/glinscott/leela-chess/releases/download/[v][0-9.a-zA-Z]*/client_linux' | head -n 1 | wget --base=https://github.com/ -i - -O client_linux && chmod +x client_linux

**Comment by lehpo** [comment]
thanks people 4 your help

i applied the changes u proposed

but i still got the same message over and over again

yesterday i got connected on my first attempt

and managed to upload some 400+ games until i got disconnected

2day i can't connect again, so probably the problem is not mine, but google's

i give up
