### ISSUE TITLE
Leela plays only one move on playchess.com, then stops

### ISSUE THREAD

**Issue by chara1ampos** [glinscott/leela-chess#538]
I named the network weights.txt and Leela 0.8 can play on Fritz 14 against other enginges. I am using the GPU version with an Nvidia Titan V, and even scored several draws and wins against Stockfish. But when playing online against other engines, Leela plays the first move, then the opponent plays the second move, and then the Leela engine stops working. It just does not play any more, and loses when the time runs out. This is a really bad bug, please fix.

**Comment by mooskagh** [comment]
Which version of the engine do you use? There was a bug that caused hang, which was fixed in May 3rd build.

**Comment by chara1ampos** [comment]
@mooskagh I was using the May 2 version. I just tried your May 5 version, but the problem remains (when playing on playchess.com). Leela plays only one move, then stops.

This does not happen when you play locally with other engines in your computer.

**Comment by chara1ampos** [comment]
I used InBetween.exe to log errors. It produced this error file:
[logfile.log](https://github.com/glinscott/leela-chess/files/1977184/logfile.log)

It seems the error may have something to do with Ponder being enabled. Any idea how to disable it?

**Comment by killerducky** [comment]
We don't support ponder yet, you need to figure out how to disable it in your GUI.

**Comment by chara1ampos** [comment]
@killerducky There is currently no way to do that in the Fritz GUI. I tried passing the command -noponder to Leela via InBetween.exe, but then Fritz is unable to load the engine at all. So currently it seems impossible to get Leela to play on playchess.com against other engines.

The GUI controls the pondering, but whatever I do, if an engine does not ponder, when it is given the order to ponder by the GUI, it does not follow the UCI protocol. 

I understand pondering is not yet supported, but in the mean time, is there a way to make Leela not quit when she is given the commands ponder or ponderhit? She could just do nothing, and then play normally when it is her turn. I think that should not be very difficult?
